name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        cd ~/website/carrousel
        git reset --hard HEAD
        git clean -fd
        git pull origin main
        rm -rf vendor/
        composer install --no-dev --optimize-autoloader --no-interaction
        php artisan migrate --force
        php artisan config:clear
        php artisan cache:clear
        php artisan route:cache
        php artisan view:cache
